# Generated by Django 3.2 on 2024-10-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compansation',
            old_name='CustomerIS',
            new_name='CustomerID',
        ),
        migrations.RenameField(
            model_name='monthlyinstallment',
            old_name='CustomerIS',
            new_name='CustomerID',
        ),
        migrations.RemoveField(
            model_name='announcements',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='announcements',
            name='License',
        ),
        migrations.RemoveField(
            model_name='announcements',
            name='NationalID',
        ),
        migrations.RemoveField(
            model_name='announcements',
            name='Resident',
        ),
        migrations.RemoveField(
            model_name='announcements',
            name='State',
        ),
        migrations.AlterField(
            model_name='customer',
            name='About',
            field=models.TextField(blank=True, null=True),
        ),
    ]
