# Generated by Django 3.2 on 2024-10-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0002_auto_20241016_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('Role', models.CharField(choices=[('SalesManager', 'SalesManager'), ('Customer Care Associate', 'Customer Care Associate'), ('Call Center Agent', 'Call Center Agent'), ('Help Desk Assistant', 'Help Desk Assistant')], max_length=200, primary_key=True, serialize=False)),
                ('Passport', models.ImageField(upload_to='Management')),
                ('DateRegistered', models.DateTimeField(auto_now_add=True)),
                ('Message', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Region',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='State',
        ),
    ]
