# Generated by Django 3.2 on 2024-10-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0003_auto_20241018_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=25)),
                ('Subject', models.CharField(max_length=50)),
                ('Message', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='administration',
            name='Passport',
            field=models.ImageField(upload_to='Management/'),
        ),
    ]
